# Generated by Django 5.0.2 on 2024-04-05 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_country_identification_type_remove_order_id_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='country',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='country',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='country',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='department',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='department',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='department',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='identification_type',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='identification_type',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='identification_type',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
    ]
