# Generated by Django 5.0.2 on 2024-03-16 05:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_cities_countries_deparments_identification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identification_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abrev', models.CharField(max_length=10)),
                ('descript', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 16, 0, 17, 24, 236078))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 16, 0, 17, 24, 236078))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='deparments',
            name='id_country',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='id_ident_type',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='id_exp_city',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='id_user',
        ),
        migrations.RenameField(
            model_name='cities',
            old_name='descrip',
            new_name='descript',
        ),
        migrations.RenameField(
            model_name='countries',
            old_name='descrip',
            new_name='descript',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 0, 17, 24, 189256)),
        ),
        migrations.AddField(
            model_name='user',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 0, 17, 24, 189256)),
        ),
        migrations.AlterField(
            model_name='cities',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 0, 17, 24, 236078)),
        ),
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cities',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 0, 17, 24, 236078)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 0, 17, 24, 236078)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='countries',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 0, 17, 24, 236078)),
        ),
        migrations.AlterField(
            model_name='students',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 0, 17, 24, 236078)),
        ),
        migrations.AlterField(
            model_name='students',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 0, 17, 24, 236078)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(null=True),
        ),
        migrations.CreateModel(
            name='Departaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('abrev', models.CharField(max_length=10)),
                ('descript', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 16, 0, 17, 24, 236078))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 16, 0, 17, 24, 236078))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.countries')),
            ],
        ),
        migrations.AlterField(
            model_name='cities',
            name='id_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.departaments'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=15)),
                ('ident_number', models.CharField(max_length=12)),
                ('address', models.CharField()),
                ('mobile', models.CharField()),
                ('create_at', models.DateTimeField(default=datetime.datetime(2024, 3, 16, 0, 17, 24, 236078))),
                ('update_at', models.DateTimeField(default=datetime.datetime(2024, 3, 16, 0, 17, 24, 236078))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_exp_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.cities')),
                ('id_ident_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.identification_types')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.user')),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='id_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.person'),
        ),
        migrations.DeleteModel(
            name='Identification_type',
        ),
        migrations.DeleteModel(
            name='Deparments',
        ),
        migrations.DeleteModel(
            name='Persons',
        ),
    ]
