# Generated by Django 5.0.2 on 2024-03-18 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_identification_types_remove_deparments_id_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 10, 59, 52, 953305)),
        ),
        migrations.AlterField(
            model_name='cities',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 10, 59, 52, 953305)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 10, 59, 52, 956338)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 10, 59, 52, 956338)),
        ),
        migrations.AlterField(
            model_name='departaments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 10, 59, 52, 955340)),
        ),
        migrations.AlterField(
            model_name='departaments',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 10, 59, 52, 955340)),
        ),
        migrations.AlterField(
            model_name='identification_types',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 10, 59, 52, 953305)),
        ),
        migrations.AlterField(
            model_name='identification_types',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 10, 59, 52, 953305)),
        ),
        migrations.AlterField(
            model_name='person',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 10, 59, 52, 950803)),
        ),
        migrations.AlterField(
            model_name='person',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 10, 59, 52, 950803)),
        ),
        migrations.AlterField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 10, 59, 52, 952799)),
        ),
        migrations.AlterField(
            model_name='students',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 10, 59, 52, 952799)),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 10, 59, 52, 831853)),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 10, 59, 52, 831853)),
        ),
    ]
